COLUMN CSVName FORMAT A15
COLUMN OLDVALUES FORMAT A15
COLUMN SYNTACTICTYPE FORMAT A15
COLUMN COLUMNWIDHT FORMAT 999
COLUMN NUMBEROFWORDS FORMAT 999
COLUMN OBSERVATION FORMAT A15
COLUMN NEWVALUES FORMAT A15
COLUMN SEMANTICCATEGORY FORMAT A25
COLUMN SEMANTICSUBCATEGORY FORMAT A25

COLUMN laTable FORMAT A15
COLUMN laColonne FORMAT A15
COLUMN dataReportTable FORMAT A20
COLUMN dataReportColonne FORMAT A20

COLUMN CSVName FORMAT A15
COLUMN OLDName FORMAT A15
COLUMN NEWName FORMAT A15
COLUMN nbrRows FORMAT 99
COLUMN nbrNullValues FORMAT 99
COLUMN nbrNotNullValues FORMAT 99
COLUMN minLenght FORMAT 99
COLUMN maxLength FORMAT 99
COLUMN nbrWords FORMAT 99
COLUMN nbrValuesVarcharType FORMAT 99
COLUMN nbrValuesNumberType FORMAT 99
COLUMN nbrValuesDateType FORMAT 99
COLUMN nbrValuesBooleanType FORMAT 99
COLUMN nbrValuesNullType FORMAT 99
COLUMN nbrOfDifferenteValues FORMAT 99
COLUMN theDominantSyntacticType FORMAT A30
COLUMN NumberOfSyntacticAnomalies FORMAT 99
COLUMN NumberOfSyntacticNormalValues FORMAT 99
COLUMN theDominantSemanticType FORMAT A30
COLUMN NumberOfSemanticAnomalies FORMAT 99
COLUMN NumberOfSemanticNormalValues FORMAT 99


COLUMN CONTINENT FORMAT A15
COLUMN PAYS FORMAT A15
COLUMN VILLE FORMAT A15
COLUMN CONTINENT_EN FORMAT A15
COLUMN PAYS_EN FORMAT A15
COLUMN VILLE_EN FORMAT A15

COLUMN COL1 FORMAT A15
COLUMN COL2 FORMAT A15
COLUMN COL3 FORMAT A15
COLUMN COL4 FORMAT A15
COLUMN COL5 FORMAT A15
COLUMN COL6 FORMAT A15
COLUMN COL7 FORMAT A15
COLUMN COL8 FORMAT A15
COLUMN COL9 FORMAT A15


COLUMN COL1_NAMES FORMAT A15
COLUMN COL2_NAMES FORMAT A15
COLUMN COL3_NAMES FORMAT A15
COLUMN COL4_NAMES FORMAT A15
COLUMN COL5_NAMES FORMAT A15
COLUMN COL6_NAMES FORMAT A15
COLUMN COL7_NAMES FORMAT A15
COLUMN COL8_NAMES FORMAT A15
COLUMN COL9_NAMES FORMAT A15

COLUMN COL1_GENDER FORMAT A4
COLUMN COL2_GENDER FORMAT A4
COLUMN COL3_GENDER FORMAT A4
COLUMN COL4_GENDER FORMAT A4
COLUMN COL5_GENDER FORMAT A4
COLUMN COL6_GENDER FORMAT A4
COLUMN COL7_GENDER FORMAT A4
COLUMN COL8_GENDER FORMAT A4
COLUMN COL9_GENDER FORMAT A4

COLUMN COL1_TEMPERATURE FORMAT 99
COLUMN COL2_TEMPERATURE FORMAT 99
COLUMN COL3_TEMPERATURE FORMAT 99
COLUMN COL4_TEMPERATURE FORMAT 99
COLUMN COL5_TEMPERATURE FORMAT 99
COLUMN COL6_TEMPERATURE FORMAT 99
COLUMN COL7_TEMPERATURE FORMAT 99
COLUMN COL8_TEMPERATURE FORMAT 99
COLUMN COL9_TEMPERATURE FORMAT 99

COLUMN COL1_DATE FORMAT A15
COLUMN COL2_DATE FORMAT A15
COLUMN COL3_DATE FORMAT A15
COLUMN COL4_DATE FORMAT A15
COLUMN COL5_DATE FORMAT A15
COLUMN COL6_DATE FORMAT A15
COLUMN COL7_DATE FORMAT A15
COLUMN COL8_DATE FORMAT A15
COLUMN COL9_DATE FORMAT A15
