set sqlblanklines on
COLUMN CSVName FORMAT A15
COLUMN OLDVALUES FORMAT A15
COLUMN SYNTACTICTYPE FORMAT A15
COLUMN COLUMNWIDHT FORMAT 999
COLUMN NUMBEROFWORDS FORMAT 999
COLUMN OBSERVATION FORMAT A15
COLUMN NEWVALUES FORMAT A15
COLUMN SEMANTICCATEGORY FORMAT A25
COLUMN SEMANTICSUBCATEGORY FORMAT A25
COLUMN laTable FORMAT A15
COLUMN laColonne FORMAT A15
COLUMN dataReportTable FORMAT A20
COLUMN dataReportColonne FORMAT A20