------------------------------------------------+
------------- DICOPAYSVILLE                     |
------------------------------------------------+
-- contient une liste non exhaustive de pays et de ville
EXEC dropTable('DICOPAYSVILLE');
CREATE TABLE DICOPAYSVILLE
(
	PAYS VARCHAR2(20),
	VILLE VARCHAR2(20),
	CONSTRAINT PK_DICOPAYSVILLE				PRIMARY KEY(PAYS,VILLE),
	CONSTRAINT CK_DICOPAYSVILLE_PAYS	CHECK(PAYS = UPPER(PAYS)),
	CONSTRAINT CK_DICOPAYSVILLE_VILLE	CHECK(VILLE = UPPER(VILLE))
);

INSERT INTO DICOPAYSVILLE VALUES ('FRANCE','PARIS');
INSERT INTO DICOPAYSVILLE VALUES ('ANGLETERRE','LONDRES');
INSERT INTO DICOPAYSVILLE VALUES ('ESPAGNE','MADRID');
INSERT INTO DICOPAYSVILLE VALUES ('ITALIE','ROME');
INSERT INTO DICOPAYSVILLE VALUES ('TUNISIE','TUNIS');
