-- ===============================================================================
-------- Université Sorbonne Paris Cité, Université Paris 13 , Institut Galiée
-------- Master 2 (M2 EID2), Informatique, Ingénieur
-------- Exploration Informatique des Données et Décisionnel
-- ===============================================================================
-------- La Data ; The Data
-------- La Donnée est le monde du futur ; Les données et le monde de l'avenir
-------- The Data is the world of the future ;  The Data and the future's world

-------- DATA -->>> Big Data, Dark Data, Open Data, ...
-- ===============================================================================
-------- Bases de Données Avancées = Advanced Databases (BDA)
-------- Entrepôts de Données = Data Warehouses (DWH, EDON)
-------- Lacs de Données = Data Lakes (LD, DL)


-------- Directeur :  Dr. M. Faouzi Boufarès (MFB)
-------- Enseignant-Chercheur Responsable

-------- Page Web : http://www.lipn.univ-paris13.fr/~boufares

-- ===============================================================================
-------- http://www.lipn.univ-paris13.fr/~boufares/Master2/*.sql
-- ===============================================================================
--   Projet  BDM : Big Data Management - Gestion des Données Massives
--
--   Data Manipulation (DM) - Manipulation de Données
--   Data Integration (DI) - Intégration de Données
--   Données structurées ; Données Semi-structurées ; Données NON structurées
--   Structured data; Semi-structured data; NON-structured data

--   Master Data Management (MDM) - Gestion des Données de Référence
--   Data Quality Managment (DQM) - Gestion de la qualité des données
--   Data Cleaning - Nettayage des données
--   Data deduplication - Elimination des doubles et des similaires

--   More semantics to better correct the data
--   Plus de sémantique afin de mieux corriger les données
-- ===============================================================================
-- ===============================================================================
--
--------=============  BIG DATA, DATA BASE, DATA WAREHOUSE =============----------
--
-- Big Data & Clound Computing : Think DIFFERENTLY, BIGGER and SMARTER !
-- The Excellence in Data Use !
-- EID : L'Excellence dans l'Investigation des Données
-- EID : Excellence in Data Investigation
--
-- ===============================================================================
-- Think DIFFERENTLY, BIGGER and SMARTER ! The Excellence in Data Use !
-- MISSION IMPOSSIBLE OU POSSIBLE ????? !!!!!!!!!!!
-- Votre mission, si vous l'acceptez, est : The Excellence in Data Use !
-- Si vous échouez, nous nierons avoir eu connaissance de vos agissements !

-- ===============================================================================
-- Les dictons du jour !
--
-- Aujourd'hui, j'arrête de fumer
-- Le TABAC t'ABAT
-- Fumer nuit grâvement à ta santé et à celle de ton entourage
--
-- M   T   Dents
-- SMILE and the World SMILES with you !
--
-- MANGER + MANGER = GROSSIR (??? M, A, N, G, E, R, O, S, S, I)
--
-- Manger & Bouger,
-- Pour votre santé mangez 5 fruits et légumes par jour
-- Pour votre santé ne mangez pas trop gras, trop salé, trop sucré
-- Pour votre santé faites une activité physique régulière
-- Pour votre santé faites 30 mn de marche par jour
-- Pour votre santé faites des BD !!!
--
-- Dr. M. Faouzi Boufarès
-- ===============================================================================
-- ===============================================================================
--   A new ETL   ETL & DQ : Extract-Transform-Load & Data-Quality
--                    Al ETL Al Jadyd
-- ===============================================================================
-- ===============================================================================

-- ===============================================================================
-- ===============================================================================
-- ===============================================================================
--   Nom du SGBD/DBMS  : ORACLE  /  DB2  /  MySQL  /  ...
--   Date de creation  : 24/10/2019
---  Lieu              : Université Sorbonne Paris Cité, Université Paris 13, Institut Galiée
-- ===============================================================================

-- MFB MFB MFB MFB MFB MFB MFB MFB MFB
-- ===============================================================================

-- Data Dictionnary for Regular Expressions
COLUMN TYPE FORMAT A15
COLUMN CATEGORY FORMAT A30
COLUMN SUBCATEGORY FORMAT A30
COLUMN REGULAREXPRESSION FORMAT A40
-- Creation of data structure
exec dropTable('DDRE');
CREATE TABLE DDRE (TYPE VARCHAR2(100),CATEGORY VARCHAR2(100), SUBCATEGORY VARCHAR2(100), REGULAREXPRESSION VARCHAR2(1000));

-- ===============================================================================
-- Le lien du testeur des expressions régulières est :
-- >>>>>>>>>>>>>>>                 https://regex101.com/
-- ===============================================================================

INSERT INTO DDRE VALUES ('VARCHAR2','CIVILITY', 'CIVILITY_FR', '^(M\.|MME|MLLE|MONSIEUR|MADAME|MADEMOISELLE)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CIVILITY', 'CIVILITY_EN', '^(M \.|MRS|MS|MISTER|MISS)$');

--INSERT INTO DDRE VALUES ('VARCHAR2(100)','GENDER', 'GENDER_FR', '^(F|M|MASCULIN|FÉMININ|FEMELLE|MALE)$');
--INSERT INTO DDRE VALUES ('VARCHAR2','GENDER', 'GENDER_FR', '^(F|M|MASCULIN|FEMININ|FEMELLE|MALE)$');

INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_TO', '^([0-9]+(\.\d+)?\s(TO|TONNES|TONNE))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_LB', '^([0-9]+(\.\d+)?\s(LB|LIVRE))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_LB', '^([0-9]+(\.\d+)?\s(LB|BOOK|LIVRE))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_OZ', '^((24|25|26|27|28|29|30|31|32|33)\s+(OZ|ONS|ONCE|ONCES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_QU', '^([0-9]+(\.\d+)?\s(QU|QUINTALS|QUINTAL))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_MGG', '^([0-9]+(\.\d+)?\s(MGG|MEGAGRAMME|MEGAGRAMME))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_MGG', '^([0-9]+(\.\d+)?\s(MGG|MEGAGRAM|MEGAGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_GG', '^([0-9]+(\.\d+)?\s(GG|GIGAGRAMMES|KILOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_GG', '^([0-9]+(\.\d+)?\s(GG|GIGAGRAM|GIGAGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_TG', '^([0-9]+(\.\d+)?\s(TG|TÉRAGRAMME|TÉERAGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_TG', '^([0-9]+(\.\d+)?\s(TG|TERAGRAM|TERAGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_PG', '^([0-9]+(\.\d+)?\s(PG|PÉTAGRAMME|PÉTAGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_PG', '^([0-9]+(\.\d+)?\s(PG|PETAGRAM|PETAGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_EG', '^([0-9]+(\.\d+)?\s(EG|EXAGRAMME|EXAGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_ZG', '^([0-9]+(\.\d+)?\s+(ZG|ZETTAGRAMME|ZETTAGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_ZG', '^([0-9]+(\.\d+)?\s+(ZG|ZETTAGRAM|ZETTAGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_YG', '^([0-9]+(\.\d+)?\s+(YO|YOTTOGRAMME|YOTTAGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_YG', '^([0-9]+(\.\d+)?\s+(YO|YOTTAGRAM|YOTTAGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_KG', '^([0-9]+(\.\d+)?\s+(KG|KILOGRAMME|KILOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_KG', '^([0-9]+(\.\d+)?\s+(KG|KILOGRAM|KILOGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_HG', '^([0-9]+(\.\d+)?\s+(HG|HECTOGRAMME|HECTOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_HG', '^([0-9]+(\.\d+)?\s+(HG|HECTOGRAM|HECTOGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_DAG', '^([0-9]+(\.\d+)?\s+(DAG|DÉCAGRAMME|DÉCAGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_DAG', '^([0-9]+(\.\d+)?\s+(DAGDECAGRAM|DECAGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_G', '^([0-9]+(\.\d+)?\s+(G|GRAMME|GRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_G', '^([0-9]+(\.\d+)?\s+(G|GRAM|GRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_DG', '^([0-9]+(\.\d+)?\s+(DG|DÉCIGRAMME|DÉCIGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_DG', '^([0-9]+(\.\d+)?\s+(DG|DECIGRAM|DECIGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_CG', '^([0-9]+(\.\d+)?\s+(CG|CENTIGRAMME|CENTIGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_CG', '^([0-9]+(\.\d+)?\s+(CG|CENTIGRAM|CENTIGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_MG', '^([0-9]+(\.\d+)?\s+(MG|MILLIGRAMME|MILLIGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_MG', '^([0-9]+(\.\d+)?\s+(MG|MILLIGRAM|MILLIGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_μG', '^([0-9]+(\.\d+)?\s+(μG|MICROGRAMME|MICROGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_μG', '^([0-9]+(\.\d+)?\s+(μG|MICROGRAM|MICROGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_NG', '^([0-9]+(\.\d+)?\s+(NG|NANOGRAMME|NANOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_NG', '^([0-9]+(\.\d+)?\s+(NG|NANOGRAM|NANOGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_PG', '^([0-9]+(\.\d+)?\s+(PG|PICOGRAMME|PICOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_PG', '^([0-9]+(\.\d+)?\s+(PG|PICOGRAM|PICOGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_FG', '^([0-9]+(\.\d+)?\s+(FG|FEMTOGRAMME|FEMTOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_FG', '^([0-9]+(\.\d+)?\s+(FG|FEMTOGRAM|FEMTOGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_AG', '^([0-9]+(\.\d+)?\s+(AG|ATTOGRAMME|ATTOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_AG', '^([0-9]+(\.\d+)?\s+(AG|ATTOGRAM|ATTOGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_ZPG', '^([0-9]+(\.\d+)?\s+(ZPG|ZEPTOGRAMME|ZEPTOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_ZPG', '^([0-9]+(\.\d+)?\s+(ZPG|ZEPTOGRAM|ZEPTOGRAMS))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_FR_YCG', '^([0-9]+(\.\d+)?\s+(YCG|YOCTOGRAMME|YOCTOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','WEIGHT', 'WEIGHT_EN_YCG', '^([0-9]+(\.\d+)?\s+(YCG|YOCTOGRAM|YOCTOGRAMS))$');

INSERT INTO DDRE VALUES ('NUMBER','TEMPERATURE', 'TEMPERATURE_CELSIUS', '^([\+-]?[0-9]+((\.|,)\d+)?\s?(°C|°CELSIUS|CELSIUS))$');
INSERT INTO DDRE VALUES ('NUMBER','TEMPERATURE', 'TEMPERATURE_FAHRENHEIT', '^([\+-]?[0-9]+((\.|,)\d+)?\s?(°F|°FAHRENHEIT|FAHRENHEIT°))$');
INSERT INTO DDRE VALUES ('NUMBER','TEMPERATURE', 'TEMPERATURE_KELVIN', '^[\+-]?[0-9]+((\.|,)\d+)?\s?((K|KELVIN))$');

INSERT INTO DDRE VALUES ('VARCHAR2','BLOODGROUP', 'BLOODGROUP', '^(A\+|A-|B\+|B-|AB\+|AB-|O\+|O-)$');

INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_YM', '^([0-9]+(\.\d+)?\s+(YM|YOTTAMÈTRE|YOTTAMÈRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_YM', '^([0-9]+(\.\d+)?\s+(YM|YOTTAMETER|YOTTAMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_ZM', '^([0-9]+(\.\d+)?\s+(ZM|ZETTAMÈTRE|ZETTAMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_ZM', '^([0-9]+(\.\d+)?\s+(ZM|ZETTAMETER|ZETTAMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_EM', '^([0-9]+(\.\d+)?\s+(EM|EXAMÈTRE|EXAMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_EM', '^([0-9]+(\.\d+)?\s+(EM|EXAMETER|EXAMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_PM', '^([0-9]+(\.\d+)?\s+(PM||PÉTAMÈTRE|PÉTAMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_PM', '^([0-9]+(\.\d+)?\s+(PM|PETAMETER|PETAMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_TM', '^([0-9]+(\.\d+)?\s+(TM|TÉRAÈTRE|TÉRAMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_TM', '^([0-9]+(\.\d+)?\s+(TM|TERAMETER|TERAMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_GM', '^([0-9]+(\.\d+)?\s+(GM|GIGAMÈTRE|GIGAMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_GM', '^([0-9]+(\.\d+)?\s+(GM|GIGAMETER|GIGAMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_MGM', '^([0-9]+(\.\d+)?\s+(MGM|MÉTÈRE|MÉGAMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_MGM', '^([0-9]+(\.\d+)?\s+(MGM|MEGAMETER|MEGAMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_KM', '^([0-9]+(\.\d+)?\s+(KM|KILOMÈTRE|KILOMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_KM', '^([0-9]+(\.\d+)?\s+(KM|KILOMETER|KILOMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_HM', '^([0-9]+(\.\d+)?\s+(HM|HECTOMÈTRE|HECTOMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_HM', '^([0-9]+(\.\d+)?\s+(HM|HECTOMETER|HECTOMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_DAM', '^([0-9]+(\.\d+)?\s+(DAM|DÉCAMÈTRE|DÉMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_DAM', '^([0-9]+(\.\d+)?\s+(DAM|DECAMETER|DECAMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_M', '^([0-9]+(\.\d+)?\s+(M|MÈTRE|MÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_M', '^([0-9]+(\.\d+)?\s+(M|METER|METERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_DM', '^([0-9]+(\.\d+)?\s+(DM|DÉCIMÈTRE|DÉCIMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_DM', '^([0-9]+(\.\d+)?\s+(DM|DECIMETER|DECIMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_CM', '^([0-9]+(\.\d+)?\s+(CM|CENTIMÈTRE|CENTIMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_CM', '^([0-9]+(\.\d+)?\s+(CM|CENTIMETER|CENTIMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_MM', '^([0-9]+(\.\d+)?\s+(MM|MILLIMÈTRE|MILLIMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_MM', '^([0-9]+(\.\d+)?\s+(MM|MILLIMETER|MILLIMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_UM', '^([0-9]+(\.\d+)?\s+(UM|MICROMÈTRE|MICROMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_UM', '^([0-9]+(\.\d+)?\s+(UM|MICROMETER|MICROMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_NM', '^([0-9]+(\.\d+)?\s+(NM|NANOMÈTRE|NANOMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_NM', '^([0-9]+(\.\d+)?\s+(NM|NANOMETER|NANOMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_PM', '^([0-9]+(\.\d+)?\s+(PM|PICOMÈTRE|PICOMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_PM', '^([0-9]+(\.\d+)?\s+(PM|PICOMETER|PICOMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_FM', '^([0-9]+(\.\d+)?\s+(FM|FEMTOMÈTRE|FEMTOMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_FM', '^([0-9]+(\.\d+)?\s+(FM|FEMTOMETER|FEMTOMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_AM', '^([0-9]+(\.\d+)?\s+(AM|ATTOMÈTRE|ATTOMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_AM', '^([0-9]+(\.\d+)?\s+(AM|ATTOMETER|ATTOMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_ZPM', '^([0-9]+(\.\d+)?\s+(ZPM|ZEPTOMÈTRE|ZEPTOMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_ZPM', '^([0-9]+(\.\d+)?\s(ZPM|ZEPTOMETER|ZEPTOMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_YCM', '^([0-9]+(\.\d+)?\s+(YCM|YOCTOMÈTRE|YOCTOMÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_EN_YCM', '^([0-9]+(\.\d+)?\s+(YCM|YOCTOMETER|YOCTOMETERS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FT', '^([0-9]+(\.\d+)?\s+(FT|FEET|FOOT))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_YD', '^([0-9]+(\.\d+)?\s+(YD|YARD|YARDS))$');
INSERT INTO DDRE VALUES ('NUMBER','SIZEDISTANCE_LENGTH', 'SIZEDISTANCE_LENGTH_FR_IN', '^([0-9]+(\.\d+)?\s+(IN|POUCE|PO|P|))$');

INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_YMOL', '^([0-9]+(\.\d+)?\s+(YMOL|YOTTAMOLE|YOTTAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_ZMOL', '^([0-9]+(\.\d+)?\s+(ZMOL|ZETTAMOLE|ZETTAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_EMOL', '^([0-9]+(\.\d+)?\s+(EMOL|EXAMOLE|EXAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_FR_PMOL', '^([0-9]+(\.\d+)?\s+(PMOL|PÉTAMOLE|PÉTAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_EN_PMOL', '^([0-9]+(\.\d+)?\s+(PMOL|PETAMOLE|PETAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_FR_TMOL', '^([0-9]+(\.\d+)?\s+(TMOL|TÉRAMOLE|TÉRAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_EN_TMOL', '^([0-9]+(\.\d+)?\s+(TMOL|TERAMOLE|TERAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_GMOL', '^([0-9]+(\.\d+)?\s+(GMOL|GIGAMOLE|GIGAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_FR_MMOL', '^([0-9]+(\.\d+)?\s+(MMOL|MÉGAMOLE|MÉGAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_EN_MMOL', '^([0-9]+(\.\d+)?\s+(MMOL|MEGAMOLE|MEGAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_KMOL', '^([0-9]+(\.\d+)?\s+(KMOL|KILOMOLE|KILOMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_HMOL', '^([0-9]+(\.\d+)?\s+(HMOL|HECTOMOLE|HECTOMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_FR_DAMOL', '^([0-9]+(\.\d+)?\s+(DAMOL|DÉCAMOLE|DÉCAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_EN_DAMOL', '^([0-9]+(\.\d+)?\s+(DAMOL|DECAMOLE|DECAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_MOL', '^([0-9]+(\.\d+)?\s+(MOL|MOLE|MOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_FR_DMOL', '^([0-9]+(\.\d+)?\s+(DMOL|DÉCAMOLE|DÉCAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_EN_DMOL', '^([0-9]+(\.\d+)?\s+(DMOL|DECAMOLE|DECAMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_CMOL', '^([0-9]+(\.\d+)?\s+(CMOL|CENTIMOLE|CENTIMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_MMOL', '^([0-9]+(\.\d+)?\s+(MMOL|MILLIMOLE|MILLIMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_UMOL', '^([0-9]+(\.\d+)?\s+(UMOL|MICROMOLE|MICROMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_NMOL', '^([0-9]+(\.\d+)?\s+(NMOL|NANOMOLE|NANOMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_PMOL', '^([0-9]+(\.\d+)?\s+(PMOL|PICOOMOLE|PICOMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_FMOL', '^([0-9]+(\.\d+)?\s+(FMOL|FEMTOMOLE|FEMTOMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_AMOL', '^([0-9]+(\.\d+)?\s+(AMOL|ATTOMOLE|ATTOMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_ZPMOL', '^([0-9]+(\.\d+)?\s+(ZPMOL|ZEPTOMOLE|ZEPTOMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','ATOMIC_MASS', 'ATOMIC_MASS_YCMOL', '^([0-9]+(\.\d+)?\s+(YCMOL|YOCTOMOLE|YOCTOMOLES))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_BOUGIE', '^([0-9]+(\.\d+)\s+(BOUGIE))$');

INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_YCD', '^([0-9]+(\.\d+)\s+(YCD|YOTTACANDELA|YOTTACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_ZCD', '^([0-9]+(\.\d+)\s+(ZCD|ZETTACANDELA|ZETTACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_ECD', '^([0-9]+(\.\d+)\s+(ECD|EXACANDELA|EXACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_FR_PCD', '^([0-9]+(\.\d+)\s+(PCD|PÉTACANDELA|PÉTACANDELA))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_EN_PCD', '^([0-9]+(\.\d+)\s+(PCD|PETACANDELA|PETACANDELA))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_FR_TCD', '^([0-9]+(\.\d+)?\s+(TCD|TÉRACANDELA|TÉERACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_EN_TCD', '^([0-9]+(\.\d+)?\s+(TCD|TERACANDELA|TERACANDELA))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_GCD', '^([0-9]+(\.\d+)?\s+(GCD|GIGACANDELA|GIGACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_FR_MGCD', '^([0-9]+(\.\d+)?\s+(MGCD|MÉGACANDELA|MÉGACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_EN_MGCD', '^([0-9]+(\.\d+)?\s+(MGCD|MEGACANDELA|MEGACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_KCD', '^([0-9]+(\.\d+)?\s+(KCD|KILOCANDELA|KILOCANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_HCD', '^([0-9]+(\.\d+)?\s+(HCD|HECTOCANDELA|HECTOCANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_FR_DACD', '^([0-9]+(\.\d+)?\s+(DACD|DÉCACANDELA|DÉECACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_EN_DACD', '^([0-9]+(\.\d+)?\s+(DACD|DECACANDELA|DECACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_CD', '^([0-9]+(\.\d+)?\s+(CD|CANDELA|CANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_FR_DCD', '^([0-9]+(\.\d+)?\s+(DCD|DÉCACANDELA|DÉCACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_EN_DCD', '^([0-9]+(\.\d+)?\s+(DCD|DECACANDELA|DECACANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_CCD', '^([0-9]+(\.\d+)?\s+(CCD|CENTICANDELA|CENTICANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_MCD', '^([0-9]+(\.\d+)?\s+(MCD|MILLICANDELA|MILLICANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_UCD', '^([0-9]+(\.\d+)?\s+(UCD|MICROCANDELA|MICROCANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_NCD', '^([0-9]+(\.\d+)?\s+(NCD|NANOCANDELA|NANOCANDELLA))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_PCD', '^([0-9]+(\.\d+)?\s+(PCD|PICOCANDELA|PICOCANDELLAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_FCD', '^([0-9]+(\.\d+)?\s+(FCD|FEMTOCANDELA|FEMTOCANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_ACD', '^([0-9]+(\.\d+)?\s+(ACD|ATTOCANDELA|ATTOCANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_ZPCD', '^([0-9]+(\.\d+)?\s+(ZPCD|ZPTOCANDELA|ZEPTOCANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','UNIT_LIGHT_INTENSITY', 'UNIT_LIGHT_INTENSITY_YCCD', '^([0-9]+(\.\d+)?\s+(YCCD|YOCTOCANDELA|YOCTOCANDELAS))$');
INSERT INTO DDRE VALUES ('NUMBER','LUMINOUS_ILLUMINANCE', 'LUMINOUS_ILLUMINANCE_LM', '^([0-9]+(\.\d+)?\s+(LM|LUMEN))$');
INSERT INTO DDRE VALUES ('NUMBER','LUMINOUS_ILLUMINANCE', 'LUMINOUS_ILLUMINANCE_LX', '^([0-9]+(\.\d+)?\s+(LX|LUX))$');
INSERT INTO DDRE VALUES ('NUMBER','LUMINOUS_ILLUMINANCE', 'LUMINOUS_ILLUMINANCE_PH', '^([0-9]+(\.\d+)?\s+(PH|PHOT))$');
INSERT INTO DDRE VALUES ('NUMBER','LUMINOUS_ILLUMINANCE', 'LUMINOUS_ILLUMINANCE_LM', '^([0-9]+(\.\d+)?\s+(LM|LUMEN))$');
INSERT INTO DDRE VALUES ('NUMBER','LUMINOUS_ILLUMINANCE', 'LUMINOUS_ILLUMINANCE_LX', '^([0-9]+(\.\d+)?\s+(LX|LUX))$');
INSERT INTO DDRE VALUES ('NUMBER','LUMINOUS_ILLUMINANCE', 'LUMINOUS_ILLUMINANCE_PH', '^([0-9]+(\.\d+)?\s+(PH|PHOT))$');

INSERT INTO DDRE VALUES ('NUMBER','TENSION', 'TENSION', '^([0-9]+(\.\d+)?\s+(V|VOLTT))$');
INSERT INTO DDRE VALUES ('NUMBER','ELECTRIC_POWER', 'ELECTRIC_POWER', '^([0-9]+(\.\d+)?\s+(A|AMPERE|AMPERES|AMPÉRES))$');
INSERT INTO DDRE VALUES ('NUMBER','POWER_WATT', 'POWER_WATT', '^([0-9]+(\.\d+)?\s+(W|WATT))$');
INSERT INTO DDRE VALUES ('NUMBER','CAPACITY', 'CAPACITY', '^([0-9]+(\.\d+)?\s+(F|FARAD))$');
INSERT INTO DDRE VALUES ('NUMBER','FREQUENCY', 'FREQUENCY', '^([0-9]+(\.\d+)?\s+(HZ|HERTZ))$');
INSERT INTO DDRE VALUES ('NUMBER','ELECTRIC_QUANTITY', 'ELECTRIC_QUANTITY', '^([0-9]+(\.\d+)?\s+(C|COULOMB))$');
INSERT INTO DDRE VALUES ('NUMBER','ENERGY', 'ENERGY', '^([0-9]+(\.\d+)?\s+(J|JOULE|JOULES))$');
INSERT INTO DDRE VALUES ('NUMBER','ELECTRIC_FIELD', 'ELECTRIC_FIELD', '^([0-9]+(\.\d+)?\s+(V\/M|VOLT-METER|VOLT-METERS|VOLT-MÈTRE|VOLT-MÈTRES))$');
INSERT INTO DDRE VALUES ('NUMBER','POWER_NEWTON', 'POWER_NEWTON', '^([0-9]+(\.\d+)?\s+(N|NEWTON|NEWTONS))$');
INSERT INTO DDRE VALUES ('NUMBER','GRAVITY', 'GRAVITY', '^([0-9]+(\.\d+)?\s+(N\/KG|NEWTON\/KILOGRAMME|NEWTONS\/KILOGRAMMES))$');
INSERT INTO DDRE VALUES ('NUMBER','ENERGY', 'CALORIE _KCAL', '^([0-9]+(\.\d+)?\s+(KCAL|KILOCALORIE|KILOCALERIES))$');
INSERT INTO DDRE VALUES ('NUMBER','ENERGY', 'CALORIE _FR_MCAL', '^([0-9]+(\.\d+)?\s+(MCAL|MÉGACALORIE|MÉGACALERIES))$');
INSERT INTO DDRE VALUES ('NUMBER','ENERGY', 'CALORIE _EN_MCAL', '^([0-9]+(\.\d+)?\s+(MCAL|MEGACALORIE|MEGACALERIES))$');
INSERT INTO DDRE VALUES ('NUMBER','ENERGY', 'CALORIE _CAL', '^([0-9]+(\.\d+)?\s+(CAL|CALORIE|CALERIES))$');
INSERT INTO DDRE VALUES ('NUMBER','ENERGY', 'FRIGORIE_FG', '^([\+-]?[0-9]+(\.\d+)?\s+(FG|FRIGORIE|FRIGORIES))$');
INSERT INTO DDRE VALUES ('NUMBER','PRESSURE_AND_CONTRAINT', 'PRESSURE_AND_CONTRAINT_HPA', '^([0-9]+(\.\d+)?\s+(HPA|HECTOPASCAL|HECTOPASCALS))$');
INSERT INTO DDRE VALUES ('NUMBER','PRESSURE_AND_CONTRAINT', 'PRESSURE_AND_CONTRAINT_KPA', '^([0-9]+(\.\d+)?\s+(KPA|KILOPASCAL|KILOPASCALS))$');
INSERT INTO DDRE VALUES ('NUMBER','PRESSURE_AND_CONTRAINT', 'PRESSURE_AND_CONTRAINT_FR_MPA', '^([0-9]+(\.\d+)?\s+(MPA|MÉGAPASCAL|MÉGAOPASCALS))$');
INSERT INTO DDRE VALUES ('NUMBER','PRESSURE_AND_CONTRAINT', 'PRESSURE_AND_CONTRAINT_EN_MPA', '^([0-9]+(\.\d+)?\s+(MPA|MEGAPASCAL|MEGAPASCALS))$');
INSERT INTO DDRE VALUES ('NUMBER','PRESSURE_AND_CONTRAINT', 'PRESSURE_AND_CONTRAINT_GPA', '^([0-9]+(\.\d+)?\s+(GPA|GIGAPASCAL|GIGAPASCALS))$');
INSERT INTO DDRE VALUES ('NUMBER','PRESSURE_AND_CONTRAINT', 'PRESSURE_AND_CONTRAINT_FR_TPA', '^([0-9]+(\.\d+)?\s+(TPA|TÉRAPASCAL|TÉRAPASCALS))$');
INSERT INTO DDRE VALUES ('NUMBER','PRESSURE_AND_CONTRAINT', 'PRESSURE_AND_CONTRAINT_EN_TPA', '^([0-9]+(\.\d+)?\s+(TPA|TERAPASCAL|TERAPASCALS))$');
INSERT INTO DDRE VALUES ('NUMBER','PRESSURE_AND_CONTRAINT', 'PRESSURE_AND_CONTRAINT_BAR', '^([0-9]+(\.\d+)?\s+(BAR|BARS))$');

INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_YS', '^([0-9]+(\.\d+)?\s+(YS|YOTTASECONDE|YOTTASECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_YS', '^([0-9]+(\.\d+)?\s+(YS|YOTTASECOND|YOTTASECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_ZS', '^([0-9]+(\.\d+)?\s+(ZS|ZETTASECONDE|ZETTASECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_ZS', '^([0-9]+(\.\d+)?\s+(ZS|ZETTASECOND|ZETTASECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_ES', '^([0-9]+(\.\d+)?\s+(ES|EXASECONDE|EXASECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_ES', '^([0-9]+(\.\d+)?\s+(ES|EXASECOND|EXASECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_PS', '^([0-9]+(\.\d+)?\s+(PS|PÉTASECONDE|PÉTASECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_PS', '^([0-9]+(\.\d+)?\s+(PS|PETASECOND|PETASECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_TS', '^([0-9]+(\.\d+)?\s+(TS|TÉRASECONDE|TÉRASECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_TS', '^([0-9]+(\.\d+)?\s+(TS|TERASECOND|TERASECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_GS', '^([0-9]+(\.\d+)?\s+(GS|GIGASECONDE|GIGASECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_GS', '^([0-9]+(\.\d+)?\s+(GS|GIGASECOND|GIGASECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_MGS', '^([0-9]+(\.\d+)?\s+(MGS|MÉGASECONDE|MÉGASECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_MGS', '^([0-9]+(\.\d+)?\s+(MGS|MEGASECOND|MEGASECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_KS', '^([0-9]+(\.\d+)?\s+(KS|KILOSECONDE|KILOSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_KS', '^([0-9]+(\.\d+)?\s+(KS|KILOSECOND|KILOSECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_HS', '^([0-9]+(\.\d+)?\s+(HS|HECTOSECONDE|HECTOSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_HS', '^([0-9]+(\.\d+)?\s+(HS|HECTOSECOND|HECTOSECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_DAS', '^([0-9]+(\.\d+)?\s+(DAS|DÉCASECONDES|DÉCASECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_DAS', '^([0-9]+(\.\d+)?\s+(DAS|DECASECONDS|DECASECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_S', '^([0-9]+(\.\d+)?\s+(S|SECONDE|SECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_S', '^([0-9]+(\.\d+)?\s+(S|SECOND|SECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_DS', '^([0-9]+(\.\d+)?\s+(DS|DÉCISECONDE|DÉCISECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_DS', '^([0-9]+(\.\d+)?\s+(DS|DCISECOND|DECISECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_CS', '^([0-9]+(\.\d+)?\s+(CS|CENTISECONDE|CENTISECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_CS', '^([0-9]+(\.\d+)?\s+(CS|CENTISECOND|CENTISECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_MS', '^([0-9]+(\.\d+)?\s+(MS|MILLLISECONDE|MILLISECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_MS', '^([0-9]+(\.\d+)?\s+(MS|MILLLISECOND|MILLISECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_US', '^([0-9]+(\.\d+)?\s+(US|MICROSECONDE|MICROSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_US', '^([0-9]+(\.\d+)?\s+(US|MICROSECOND|MICROSECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_NS', '^([0-9]+(\.\d+)?\s+(NS|NANOSECONDE|NANOSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_NS', '^([0-9]+(\.\d+)?\s+(NS|NANOSECOND|NANOSECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_PS', '^([0-9]+(\.\d+)?\s+(PS|PICOSECONDE|PICOSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_PS', '^([0-9]+(\.\d+)?\s+(PS|PICOSECOND|PICOSECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_FS', '^([0-9]+(\.\d+)?\s+(FS|FEMTOSECONDE|FEMTOSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_FS', '^([0-9]+(\.\d+)?\s+(FS|FEMTOSECOND|FEMTOSECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_AS', '^([0-9]+(\.\d+)?\s+(AS|ATTOSECONDE|ATTOSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_AS', '^([0-9]+(\.\d+)?\s+(AS|ATTOSECOND|ATTOSECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_ZPS', '^([0-9]+(\.\d+)?\s+(ZPS|ZEPTOSECONDE|ZEPTOSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_ZPS', '^([0-9]+(\.\d+)?\s+(ZPS|ZEPTOSECOND|ZEPTOSECONDS))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_FR_YCS', '^([0-9]+(\.\d+)?\s+(YCS|YOCTOSECONDE|YOCTOSECONDES))$');
INSERT INTO DDRE VALUES ('NUMBER','TIME_SECONDS', 'TIME_SECONDS_EN_YCS', '^([0-9]+(\.\d+)?\s+(YCS|YOCTOSECOND|YOCTOSECONDS))$');

INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'CENTURY_FR_LIGHT', '^([0-9]+(\.\d+)?\s+(SIECLE_LUMIERE|SIECLE_LUMIERE))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'CENTURY_EN_LIGHT', '^([0-9]+(\.\d+)?\s+(CENTURY_LIGHT|CENTERIES_LIGHT))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'LIGHT_FR_YEAR', '^([0-9]+(\.\d+)?\s+(ANNEE_LUMIERE|ANNEES_LUMIERE))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'LIGHT_EN_YEAR', '^([0-9]+(\.\d+)?\s+(YEAR_LIGHT|YEARS_LIGHT))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'DAY_FR_LIGHT', '^([0-9]+(\.\d+)?\s+(JOUR_LUMIERE|JOURS_LUMIERE))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'DAY_EN_LIGHT', '^([0-9]+(\.\d+)?\s+(DAY_LIGHT|DAYS_LIGHT))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'HOUR_LIGHT', '^([0-9]+(\.\d+)?\s+(HEURE_LUMIERE|HEURES_LUMIERE))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'MINUTE_FR_LIGHT', '^([0-9]+(\.\d+)?\s+(MINUTE_LUMIERE|MINUTES_LUMIERE))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'SECOND_FR_LIGHT', '^([0-9]+(\.\d+)?\s+(SECONDE_LUMIERE|SECONDES_LUMIERE))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'SECOND_EN_LIGHT', '^([0-9]+(\.\d+)?\s+(SECOND_LUMIERE|SECONDS_LUMIERE))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'PARSC_PC', '^([0-9]+(\.\d+)?\s+(PC|PARSEC|PARSECS))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'PARSC_KPC', '^([0-9]+(\.\d+)?\s+(KPC|PARSEC|PARSECS))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'PARSC_FR_MPC', '^([0-9]+(\.\d+)?\s+(MPC|MÉGAPARSEC|MÉGAPARSECS))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'PARSC_EN_MPC', '^([0-9]+(\.\d+)?\s+(MPC|MEGAPARSEC|MEGAPARSECS))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'PARSC_GPC', '^([0-9]+(\.\d+)?\s+(GPC|GIGAPARSEC|GIGAPARSECS))$');
INSERT INTO DDRE VALUES ('NUMBER','ASTRONOMY_DISTANCE', 'ASTRONOMICAL_UNIT_AU', '^([0-9]+(\.\d+)?\s+(AU|UA))$');

INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_KM/H', '^([0-9]+(\.\d+)?\s+(KM\/H|KILOMÈTRE\/HEURE|KILOMÈTRES\/HEURE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_KM/H', '^([0-9]+(\.\d+)?\s+(KM\/H|KILOMETER\/HOUR|KILOMETERS\/HOUR))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_M/H', '^([0-9]+(\.\d+)?\s+(M\/H|MÈTRE\/HEURE|MÈTRES\/HEURE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_M/H', '^([0-9]+(\.\d+)?\s+(M\/H|METER\/HOUR|METERS\/HOUR))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_MP/H', '^([0-9]+(\.\d+)?\s+(MP\/H|MILLE\/HEURE|MILLE\/HEURE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_MP/H', '^([0-9]+(\.\d+)?\s+(MP\/H|MILE\/HOUR|MILE\/HOUR))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_FT/H', '^([0-9]+(\.\d+)?\s+(FT\/H|PIERD\/HEURE|PIERDS\/HEURE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_FT/H', '^([0-9]+(\.\d+)?\s+(FT\/H|FEET\/HOUR|FOOT\/HOUR))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_KM/MIN', '^([0-9]+(\.\d+)?\s+(KM\/MIN|KILOMÈTRE\/MINUTE|KILOMÈTRES\/MINUTE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_KM/MIN', '^([0-9]+(\.\d+)?\s+(KM\/MIN|KILOMETER\/MINUTE|KILOMETERS\/MINUTE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_M/MIN', '^([0-9]+(\.\d+)?\s+(M\/MIN|MÈTRE\/MINUTE|MÈTRES\/MINUTE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_M/MIN', '^([0-9]+(\.\d+)?\s+(M\/MIN|METER\/MINUTE|METERS\/MINUTE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_MP/MIN', '^([0-9]+(\.\d+)?\s+(MP\/MIN|MILLE\/MINUTE|MILLE\/MINUTE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_MP/MIN', '^([0-9]+(\.\d+)?\s+(MP\/MIN|MILE\/MINUTE|MILE\/MINUTE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_FT/MIN', '^([0-9]+(\.\d+)?\s+(FT\/MIN|PIED\/MINITE|PIEDS\/MINUTE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_FT/MIN', '^([0-9]+(\.\d+)?\s+(FT\/MIN|FOOT\/MINITE|FEET\/MINUTE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_KM/S', '^([0-9]+(\.\d+)?\s+(KM\/S|KILOMÈTRE\/SECONDE|KILOMÈTRES\/SECONDE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_KM/S', '^([0-9]+(\.\d+)?\s+(KM\/S|KILOMETER\/SECOND|KILOMETERS\/SECOND))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_M/S', '^([0-9]+(\.\d+)?\s+(M\/S|MÈTRE\/SECONDE|MÈTRES\/SECONDE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_M/S', '^([0-9]+(\.\d+)?\s+(M\/S|METER\/SECOND|METERS\/SECOND))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_MP/S', '^([0-9]+(\.\d+)?\s+(MP\/S|MILLE\/SECONDE|MILLES\/SECONDE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_MP/S', '^([0-9]+(\.\d+)?\s+(MP\/S|MILE\/SECOND|MILES\/SECOND))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_FT/S', '^([0-9]+(\.\d+)?\s+(FT\/S|PIED\/SECONDE|PIEDS\/SECONDE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_FT/S', '^([0-9]+(\.\d+)?\s+(FT\/S|FOOT\/SECOND|FEET\/SECOND))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_KT', '^([0-9]+(\.\d+)?\s+(KT|NŒUD|NOEUDS))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_SEAMILES/H', '^([0-9]+(\.\d+)?\s+(SEAMILLE\/HEURE|MILLE_NAUTIQUE\/HEURE|MILLES_NAUTIQUES\/HEURE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_SEAMILES/H', '^([0-9]+(\.\d+)?\s+(SEAMILES\/HOUR|MILE_NAUTIQUE\/HOUR|MILES_NAUTIQUES\/HOUR))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_FR_MPH', '^([0-9]+(\.\d+)?\s+(MPH|MILLE\/HEURE|MILLES\/HEURE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPEED', 'SPEED_EN_MPH', '^([0-9]+(\.\d+)?\s+(MPH|MILE\/HOUR|MILES\/HOUR))$');

INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_FR_SEC/KM', '^([0-9]+(\.\d+)?\s+(S\/KM|SECONDE\/KILOMÈTRE|SECONDES\/KILOMÈTRE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_EN_SEC/KM', '^([0-9]+(\.\d+)?\s+(S\/KM|SECOND\/KILOMETER|SECONDS\/KILOMETER))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_FR_SEC/M', '^([0-9]+(\.\d+)?\s+(S\/M|SECOND\/MÈTRE|SECONDS\/MÈTRE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_EN_SEC/M', '^([0-9]+(\.\d+)?\s+(S\/M|SECOND\/METER|SECONDS\/METER))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_FR_SEC/MILE', '^([0-9]+(\.\d+)?\s+(S\/MILE|SECONDE\/MILLE|SECONDS\/MILLE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_EN_SEC/MILE', '^([0-9]+(\.\d+)?\s+(S\/MILE|SECONDE\/MILE|SECONDS\/MILE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_FR_MIN/KM', '^([0-9]+(\.\d+)?\s+(MIN\/KM|MINUTE\/KILOMÈTRE|MINUTES\/KILOMÈTRE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_EN_MIN/KM', '^([0-9]+(\.\d+)?\s+(MIN\/KM|MINUTE\/KILOMETER|MINUTES\/KILOMETER))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_FR_MIN/M', '^([0-9]+(\.\d+)?\s+(MIN\/M|MINUTE\/MÈTRE|MINUTES\/MÈTRE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_EN_MIN/M', '^([0-9]+(\.\d+)?\s+(MIN\/M|MINUTE\/METER|MINUTES\/METER))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_FR_MIN/MILE', '^([0-9]+(\.\d+)?\s+(MIN\/MILE|MINUTE\/MILLE|MINUTES\/MILLE))$');
INSERT INTO DDRE VALUES ('NUMBER','SPORT_UNIT', 'SPORT_UNIT_EN_MIN/MILE', '^([0-9]+(\.\d+)?\s+(MIN\/MILE|MINUTE\/MILE|MINUTES\/MILE))$');

INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'SIZE_JACKETS_COATS_PARKAS_COSTUMES)', '^(XS|S|M|L|XL|XXL|XXXL)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'SIZE_SWEATERS_T-SHIRT_SWEETS_POLOS', '^((XS|S|M|L|XL|XXL|XXXL|1|2|3|4|5|6|7))$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'CLOTHING_SIZE_NUM', '^(32|35|36|37|38|39|40|41|42|43|44||45|46|47|48|49|50|51|52)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'AMERICAN_SIZE_MAN ', '^(XXS|XS|S|M|L|XL|XXL)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'AMERICAN_SIZE_WOMEN', '^(S|M|L|XL|XXL|XXXL|XXXXL)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_BE', '^(34|36|38|40|42|44|46|48|50|52)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_FR', '^(34|36|38|40|42|44|46|48|50|52)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_ES', '^(34|36|38|40|42|44|46|48|50|52)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_PT', '^(34|36|38|40|42|44|46|48|50|52)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_US', '^(2|4|6|8|10|12|14|16|18|20)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_GB', '^(6|8|10|12|14|16|18|20|22|24)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_AE', '^(32|34|36|38|40|42|44|46|48|50)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_NL', '^(32|34|36|38|40|42|44|46|48|50)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_SE', '^(32|34|36|38|40|42|44|46|48|50)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_IT', '^(38|40|42|44|46|48|50|52|54|56)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_DRESS_AT', '^(32|34|36|38|40|42|44|46|48|50)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'UNIV_SIZE_DRESS', '^(XS|S|M|M|L|L|XL|XL|XXL|3XL)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_WOMEN_GLOVES_EUR', '^(6,5|7|7,5|8|8,5|9|9,5|10)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'SIZE_WOMEN_GLOVES_AM', '^(S|M|L|XL)$');
INSERT INTO DDRE VALUES ('NUMBER','CLOTHING_SIZE', 'SIZE_MEN_GLOVES_EUR', '^(6,5|7|7,5|8|8,5|9|9,5|10)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'SIZE_MEN_GLOVES_AM', '^(XS|S|M|L|XL|XXL)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'SIZE_MEN_TROUSSERS_US', '^(XS|S|M|L|XL|XXL)$');
INSERT INTO DDRE VALUES ('VARCHAR2','CLOTHING_SIZE', 'SIZE_TROUSSERS_MEN_FR', '^(36/38|40/42|44/46|48/50|52/54|56/58)$');

INSERT INTO DDRE VALUES ('NUMBER','SIZE_SHOES', 'SIZE_WOMEN_SHOES_FR', '^(30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50)$');
INSERT INTO DDRE VALUES ('NUMBER','SIZE_SHOES', 'SIZE_MEN_SHOES_FR', '^(30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50)$');
INSERT INTO DDRE VALUES ('NUMBER','SIZE_SHOES', 'SIZE_SHOES_EUR', '^(35|36|37|38|39|40|41|42|43|44||45|46|47|48|49|50|51|52)$');
INSERT INTO DDRE VALUES ('NUMBER','SIZE_SHOES', 'SIZE_SHOES_US', '^(0,5|1,5|2,5|3,5|4,5|5.5|6,5|7.5|8,5|9,5|10,5|11,5|12,5|13,5|14,5|15,5|16,5|17,5)$');
INSERT INTO DDRE VALUES ('NUMBER','SIZE_SHOES', 'SIZE_SHOES_IT', '^(29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49)$');
INSERT INTO DDRE VALUES ('NUMBER','SIZE_SHOES', 'SIZE_SHOES_JP', '^(16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36)$');
INSERT INTO DDRE VALUES ('NUMBER','SIZE_SHOES', 'SIZE_SHOES_UK', '^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17)$');

INSERT INTO DDRE VALUES ('NUMBER','JEWELRY', 'DIAMANT_CARAT', '^([0-9]+(\.\d+)?\s+(CARAT|CARATS|KT|K|CT))$');
INSERT INTO DDRE VALUES ('NUMBER','JEWELRY', 'OR_CARAT', '^([0-9]+(\.\d+)?\s+(CARAT|CARATS|KT|K|CT))$');
INSERT INTO DDRE VALUES ('NUMBER','JEWELRY', 'ARGENT_CARAT', '^([0-9]+(\.\d+)?\s+(CARAT|CARATS|KT|K|CT))$');

INSERT INTO DDRE VALUES ('NUMBER','HEARING_NOISE', 'HEARING_NOISE_FR_DB', '^([0-9]+(\.\d+)?\s+(DÉCIBEL|DB|DÉCIBELS))$');
INSERT INTO DDRE VALUES ('NUMBER','HEARING_NOISE', 'HEARING_NOISE_EN_DB', '^([0-9]+(\.\d+)?\s+(DECIBEL|DB|DECIBELS))$');
INSERT INTO DDRE VALUES ('NUMBER','HEARING_NOISE', 'HEARING_NOISE_FR_DB(A)', '^([0-9]+(\.\d+)?\s+(DÉCIBELA|DB\(A\)|DÉCIBELSA))$');
INSERT INTO DDRE VALUES ('NUMBER','HEARING_NOISE', 'HEARING_NOISE_EN_DB(A)', '^([0-9]+(\.\d+)?\s+(DECIBELA|DB\(A\)|DECIBELSA))$');
INSERT INTO DDRE VALUES ('NUMBER','HEARING_NOISE', 'HEARING_NOISE_EPND', '^([0-9]+(\.\d+)?\s+(EPNDB))$');
INSERT INTO DDRE VALUES ('NUMBER','HEARING_NOISE', 'HEARING_NOISE_LDEN', '^([0-9]+(\.\d+)?\s+(LDEN))$');
INSERT INTO DDRE VALUES ('NUMBER','HEARING_NOISE', 'HEARING_NOISE_NAX', '^([0-9]+(\.\d+)?\s+(NAX))$');

INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_KFLOPS', '^([0-9]+(\.\d+)?\s+(KFLOPS|KIOFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_FR_MFLOPS', '^([0-9]+(\.\d+)?\s+(MFLOPS|MÉGAFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_EN_MFLOPS', '^([0-9]+(\.\d+)?\s+(MFLOPS|MEGAFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_GFLOPS', '^([0-9]+(\.\d+)?\s+(GFLOPS|GIGAFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_TFLOPS', '^([0-9]+(\.\d+)?\s+(TFLOPS|TERAFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_FR_PFLOPS', '^([0-9]+(\.\d+)?\s+(PFLOPS|PÉTAFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_EN_PFLOPS', '^([0-9]+(\.\d+)?\s+(PFLOPS|PETAFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_EFLOPS', '^([0-9]+(\.\d+)?\s+(EFLOPS|EXAFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_ZFLOPS', '^([0-9]+(\.\d+)?\s+(ZFLOPS|ZETTAFLOPS))$');
INSERT INTO DDRE VALUES ('NUMBER','FLOATING_PONIT_PROCESSING', 'FLOATING_PONIT_PROCESSING_YFLOPS', '^([0-9]+(\.\d+)?\s+(YFLOPS|YOTTAFLOPS))$');

INSERT INTO DDRE VALUES ('NUMBER','IMAGE_UNIT', 'IMAGE_SX', '^([0-9]+(\.\d+)?\s+(SX|SIXEL|SIXELS|SIX_PIXELS))$');
INSERT INTO DDRE VALUES ('NUMBER','IMAGE_UNIT', 'IMAGE_DX', '^([0-9]+(\.\d+)?\s+(DX|DEXEL|DEXELS|DEPTH_PIXELS))$');
INSERT INTO DDRE VALUES ('NUMBER','IMAGE_UNIT', 'IMAGE_VX', '^([0-9]+(\.\d+)?\s+(VX|VXEL|VOXEL))$');

INSERT INTO DDRE VALUES ('NUMBER','COMPUTERSTORAGECAPACITY', 'COMPUTERSTORAGECAPACITY_KO', '^([0-9]+(\.\d+)?\s+(KO|KB|KILO-OCTETS))$');
INSERT INTO DDRE VALUES ('NUMBER','COMPUTERSTORAGECAPACITY', 'COMPUTERSTORAGECAPACITY_MO', '^([0-9]+(\.\d+)?\s+(MO|MB|MEGA-OCTETS))$');
INSERT INTO DDRE VALUES ('NUMBER','COMPUTERSTORAGECAPACITY', 'COMPUTERSTORAGECAPACITY_GO', '^([0-9]+(\.\d+)?\s+(GO|GB|GIGA-OCTETS))$');
INSERT INTO DDRE VALUES ('NUMBER','COMPUTERSTORAGECAPACITY', 'COMPUTERSTORAGECAPACITY_O', '^([0-9]+(\.\d+)?\s+(O|OCTETS))$');

INSERT INTO DDRE VALUES ('NUMBER','ODOR', 'ODOR_FR', '^([0-9]+(\.\d+)?\s+(OLFACTOMÉTRIE|OLFACTOMÉTRIES))$');
INSERT INTO DDRE VALUES ('NUMBER','ODOR', 'ODOR_EN', '^([0-9]+(\.\d+)?\s+(OLFACTOMETRIE|OLFACTOMERIES))$');

INSERT INTO DDRE VALUES ('NUMBER','VISON', 'VISON ', '^([0-9]+(\.\d+)?\s+(DIOPTRIE|DIOPTRIES))$');

INSERT INTO DDRE VALUES ('NUMBER','HEARTBEAT', 'HEARTBEAT_FR', '^([0-9]+(\.\d+)?\s+(BPM|BATTEMENT/MINUTE|BATTEMENT/MIN))$');
INSERT INTO DDRE VALUES ('NUMBER','HEARTBEAT', 'HEARTBEAT_EN', '^([0-9]+(\.\d+)?\s+(BPM|BEAT/MINUTE|BEAT/MIN))$');

-- @ludo ++
-- new column for type
INSERT INTO DDRE VALUES ('DATE','DATE','DATE_FR', '([0-2][0-9]|3[0-1])-(0[0-9]|1[0-2])-[0-9]{4}');
INSERT INTO DDRE VALUES ('DATE','DATE','DATE_ISO', '[0-9]{4}-(0[0-9]|1[0-2])-([0-2][0-9]|3[0-1])');
INSERT INTO DDRE VALUES ('DATE','DATE','DATE_USA', '(0[0-9]|1[0-2])-([0-2][0-9]|3[0-1])-[0-9]{2}');
--jj/mm/aaaa fr
--aaaa-mm-jj iso
--mm-jj-aa usa
INSERT INTO DDRE VALUES ('NUMBER','AGE','AGE','^[0-9]{2}$' );

INSERT INTO DDRE VALUES ('VARCHAR2','NAMES','FIRSTNAME', '^[a-z����]{2,50}$' );
INSERT INTO DDRE VALUES ('VARCHAR2','NAMES','LASTNAME', '^[A-Z����]{2,50}$' );
INSERT INTO DDRE VALUES ('VARCHAR2','EMAIL','EMAIL', '^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$' );
-- INSERT INTO DDRE VALUES ('VARCHAR2','NAMES','CITY', '^\s*[a-zA-Z]{1}[0-9a-zA-Z][0-9a-zA-Z -.=#/]*$' );
INSERT INTO DDRE VALUES ('VARCHAR2','NAMES','CITY', '^[[:alpha:] ]+$' );

INSERT INTO DDRE VALUES ('VARCHAR2','GENDER', 'GENDER_FR', '^(m|f|masculin|feminin|F|M|MASCULIN|FEMININ|FEMELLE|MALE)$');



COMMIT;
