------------------------------------------------+
------------- DICOMOIS                          |
------------------------------------------------+
-- contient une liste non exhaustive de pays et de ville
EXEC dropTable('DICOMOIS');
CREATE TABLE DICOMOIS
(
	NUM VARCHAR2(20),
	MOIS_FR VARCHAR2(20),
  MOIS_EN VARCHAR2(20),
	CONSTRAINT PK_DICOMOIS				PRIMARY KEY(NUM)
);

INSERT INTO DICOMOIS VALUES ('01','JANVIER','JANUARY');
INSERT INTO DICOMOIS VALUES ('02','février','FEBRUARY');
INSERT INTO DICOMOIS VALUES ('03','MARS','MARCH');
INSERT INTO DICOMOIS VALUES ('04','AVRIL','APRIL');
INSERT INTO DICOMOIS VALUES ('05','MAI','MAY');
INSERT INTO DICOMOIS VALUES ('06','JUIN','JUNE');
INSERT INTO DICOMOIS VALUES ('07','JUILLET','JULY');
INSERT INTO DICOMOIS VALUES ('08','août','AUGUST');
INSERT INTO DICOMOIS VALUES ('09','SEPTEMBRE','SEPTEMBER');
INSERT INTO DICOMOIS VALUES ('10','OCTOBRE','OCTOBER');
INSERT INTO DICOMOIS VALUES ('11','NOVEMBRE','NOVEMBER');
INSERT INTO DICOMOIS VALUES ('12','décembre','DECEMBER');
