COLUMN CSVName FORMAT A15
COLUMN OLDVALUES FORMAT A15
COLUMN SYNTACTICTYPE FORMAT A15
COLUMN COLUMNWIDHT FORMAT 999
COLUMN NUMBEROFWORDS FORMAT 999
COLUMN OBSERVATION FORMAT A15
COLUMN NEWVALUES FORMAT A15
COLUMN SEMANTICCATEGORY FORMAT A25
COLUMN SEMANTICSUBCATEGORY FORMAT A25

COLUMN laTable FORMAT A15
COLUMN laColonne FORMAT A15
COLUMN dataReportTable FORMAT A20
COLUMN dataReportColonne FORMAT A20

COLUMN CSVName FORMAT A15
COLUMN OLDName FORMAT A15
COLUMN NEWName FORMAT A15
COLUMN nbrRows FORMAT 999
COLUMN nbrNullValues FORMAT 999
COLUMN nbrNotNullValues FORMAT 999
COLUMN minLength FORMAT 999
COLUMN maxLength FORMAT 999
COLUMN nbrWords FORMAT 999
COLUMN nbrValuesVarcharType FORMAT 999
COLUMN nbrValuesNumberType FORMAT 999
COLUMN nbrValuesDateType FORMAT 999
COLUMN nbrValuesBooleanType FORMAT 999
COLUMN nbrValuesNullType FORMAT 999
COLUMN nbrOfDifferenteValues FORMAT 999
COLUMN theDominantSyntacticType FORMAT A30
COLUMN NumberOfSyntacticAnomalies FORMAT 999
COLUMN NumberOfSyntacticNormalValues FORMAT 999
COLUMN theDominantSemanticType FORMAT A30
COLUMN NumberOfSemanticAnomalies FORMAT 999
COLUMN NumberOfSemanticNormalValues FORMAT 999


COLUMN CONTINENT FORMAT A15
COLUMN PAYS FORMAT A15
COLUMN VILLE FORMAT A15
COLUMN CONTINENT_EN FORMAT A15
COLUMN PAYS_EN FORMAT A15
COLUMN VILLE_EN FORMAT A15

COLUMN COL FORMAT A200
-----------------------------------COL1
COLUMN COL1 FORMAT A15
COLUMN COL2 FORMAT A15
COLUMN COL3 FORMAT A15
COLUMN COL4 FORMAT A15
COLUMN COL5 FORMAT A15
COLUMN COL6 FORMAT A15
COLUMN COL7 FORMAT A15
COLUMN COL8 FORMAT A15
COLUMN COL9 FORMAT A15

COLUMN COL10 FORMAT A15
COLUMN COL11 FORMAT A15
COLUMN COL12 FORMAT A15
COLUMN COL13 FORMAT A15
COLUMN COL14 FORMAT A15
COLUMN COL15 FORMAT A15

-----------------------------------COL1_NAMES
COLUMN COL1_NAMES FORMAT A15
COLUMN COL2_NAMES FORMAT A15
COLUMN COL3_NAMES FORMAT A15
COLUMN COL4_NAMES FORMAT A15
COLUMN COL5_NAMES FORMAT A15
COLUMN COL6_NAMES FORMAT A15
COLUMN COL7_NAMES FORMAT A15
COLUMN COL8_NAMES FORMAT A15
COLUMN COL9_NAMES FORMAT A15

COLUMN COL10_NAMES FORMAT A15
COLUMN COL11_NAMES FORMAT A15
COLUMN COL12_NAMES FORMAT A15
COLUMN COL13_NAMES FORMAT A15
COLUMN COL14_NAMES FORMAT A15
COLUMN COL15_NAMES FORMAT A15

-----------------------------------COL1_GENDER
COLUMN COL1_GENDER FORMAT A4
COLUMN COL2_GENDER FORMAT A4
COLUMN COL3_GENDER FORMAT A4
COLUMN COL4_GENDER FORMAT A4
COLUMN COL5_GENDER FORMAT A4
COLUMN COL6_GENDER FORMAT A4
COLUMN COL7_GENDER FORMAT A4
COLUMN COL8_GENDER FORMAT A4
COLUMN COL9_GENDER FORMAT A4

COLUMN COL10_GENDER FORMAT A4
COLUMN COL11_GENDER FORMAT A4
COLUMN COL12_GENDER FORMAT A4
COLUMN COL13_GENDER FORMAT A4
COLUMN COL14_GENDER FORMAT A4
COLUMN COL15_GENDER FORMAT A4

-----------------------------------COL1_TEMPERATURE
COLUMN COL1_TEMPERATURE FORMAT 999
COLUMN COL2_TEMPERATURE FORMAT 999
COLUMN COL3_TEMPERATURE FORMAT 999
COLUMN COL4_TEMPERATURE FORMAT 999
COLUMN COL5_TEMPERATURE FORMAT 999
COLUMN COL6_TEMPERATURE FORMAT 999
COLUMN COL7_TEMPERATURE FORMAT 999
COLUMN COL8_TEMPERATURE FORMAT 999
COLUMN COL9_TEMPERATURE FORMAT 999

COLUMN COL10_TEMPERATURE FORMAT 999
COLUMN COL11_TEMPERATURE FORMAT 999
COLUMN COL12_TEMPERATURE FORMAT 999
COLUMN COL13_TEMPERATURE FORMAT 999
COLUMN COL14_TEMPERATURE FORMAT 999
COLUMN COL15_TEMPERATURE FORMAT 999

-----------------------------------COL1_DATE
COLUMN COL1_DATE FORMAT A15
COLUMN COL2_DATE FORMAT A15
COLUMN COL3_DATE FORMAT A15
COLUMN COL4_DATE FORMAT A15
COLUMN COL5_DATE FORMAT A15
COLUMN COL6_DATE FORMAT A15
COLUMN COL7_DATE FORMAT A15
COLUMN COL8_DATE FORMAT A15
COLUMN COL9_DATE FORMAT A15

COLUMN COL10_DATE FORMAT A15
COLUMN COL11_DATE FORMAT A15
COLUMN COL12_DATE FORMAT A15
COLUMN COL13_DATE FORMAT A15
COLUMN COL14_DATE FORMAT A15
COLUMN COL15_DATE FORMAT A15


----------------------------------- SemanticDependencies
COLUMN TableName             FORMAT A15
COLUMN LEFTCOL               FORMAT A25
COLUMN SEMANTICDEPENDENCY    FORMAT A30
COLUMN RIGHTCOL              FORMAT A25
COLUMN PERCENTAGE            FORMAT 999